spring.application.name=LeMinhHoc

# Config cho kết nối MongoDB khi chạy local (không qua Docker)
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=NNPTUD-S3
spring.data.mongodb.username=admin
spring.data.mongodb.password=123456
spring.data.mongodb.authentication-database=admin
